version: '3.8'

services:
  database:
    container_name: sgu-database
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userback
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  backend:
    container_name: sgu-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
      tags: ["server:1.0-sgu"]
    environment:
      SERVER_PORT: 8000
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: userback
      DB_USER: root
      DB_PASS: root
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - sgu-net

  frontend:
    container_name: sgu-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
      tags: ["client:1.0-sgu"]
      args:
        API_HOST: localhost  # <-- CAMBIAR DE 'backend' A 'localhost'
        API_PORT: 8000
        API_BASE: /api/usuarios
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
  sgu-volume:

networks:
  sgu-net:
    driver: bridge
